FROM rust:1.79-alpine
WORKDIR /etc/jobtrek/sw
RUN apk add build-base
RUN cargo install ast-grep --locked
RUN apk add vim fish fd musl-dev git

RUN rustup component add rustfmt
RUN rustup component add clippy
RUN echo "map - :E<CR>" >> ~/.vimrc
RUN echo -e "[user]\n\tname = \"test\"\n\temail = \"test@example.com\"" > ~/.gitconfig
RUN echo -e "/src\n/target" > .gitignore

COPY sgconfig.yml sgconfig.yml
COPY ast-grep-rules ast-grep-rules
COPY test/test test
COPY test/expected test_expected

COPY Cargo.* ./
COPY src src

RUN git init && git add . && git commit -m "Initial commit"
ENTRYPOINT ["tail", "-f", "/dev/null"]

