FROM rust:1.79-alpine
WORKDIR /etc/jobtrek/sw
RUN apk add build-base
RUN cargo install ast-grep --locked
RUN apk add vim fastfetch fish fd musl-dev git

RUN rustup component add rustfmt
RUN rustup component add clippy
RUN mkdir -p ~/.config/fish
RUN echo "alias \"cls=clear && fastfetch\"" >> ~/.config/fish/config.fish
RUN echo "map - :E<CR>" >> ~/.vimrc
RUN echo -e "[user]\n\tname = \"test\"\n\temail = \"test@example.com\"" > ~/.gitconfig

COPY sgconfig.yml sgconfig.yml
COPY ast-grep-rules ast-grep-rules
COPY test test

COPY Cargo.* ./
COPY src src

RUN git init && git add . && git commit -m "Initial commit"
ENTRYPOINT ["tail", "-f", "/dev/null"]

