# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Continuous integration pipeline
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_code_formatting:
    name: Code formatting with fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo fmt --all -- --check --verbose

  rust_code_linter:
    name: Code linting with clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo clippy --all-targets --all-features

  rust_code_tests:
    name: Rust build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update stable && rustup default stable
      - run: sudo apt-get update && sudo apt-get install -y fd-find git
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: test/e2e.sh
