# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Continuous integration pipeline
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-debug
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  compile_and_run_a:
    name: Compile and run a.rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: rustc src/a.rs
      - run: ./a

